database-rider/database-rider

rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSetExecutor.java
rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
rider-core/src/test/java/com/github/database/rider/core/exporter/SingleExportDataSetIt.java

If test only export dataset via annotation then connection can not be established. #19

ExportDataSet can not to establish connection

---

rider-core/pom.xml
rider-core/src/main/java/com/github/database/rider/core/api/dataset/ScriptableTable.java
rider-core/src/test/java/com/github/database/rider/core/ScriptReplacementsIt.java
rider-core/src/test/java/com/github/database/rider/core/api/dataset/ScriptableTableTest.java

+ No algorithm found for <XYZ> in ScriptableTable, added test, added mockito test depedency in rider-core
Hi @rmpestano ,
I added the warning when no scriptengine was resolved at ScriptableTable#getScriptEngine(String).

Issue #53 pull request

---

rider-core/src/test/resources/datasets/yml/colonContent-replacements.yml

Hi @rmpestano ,
a test resource is missing...

+ add test resource for ScriptReplacementsIt

---

rider-core/src/main/java/com/github/database/rider/core/api/dataset/SeedStrategy.java
rider-core/src/test/java/com/github/database/rider/core/DatabaseRiderIt.java

Seed strategy for truncate insert

---

README.adoc

fixed artifactId in readme
```
<dependency>
<groupId>com.github.database-rider</groupId>
<artifactId>database-rider</artifactId>
<version>1.2.2</version>
<scope>test</scope>
</dependency>
```

Incorrect artifactId in readme

---

rider-cdi/src/test/java/com/github/database/rider/cdi/ExportDataSetCDIIt.java
rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSetFormat.java
rider-core/src/main/java/com/github/database/rider/core/exporter/DataSetExporter.java
rider-core/src/test/java/com/github/database/rider/core/exporter/ExportDataSetIt.java
rider-core/src/test/java/com/github/database/rider/core/exporter/ExportNullPropertiesIt.java
rider-junit5/src/test/java/com/github/database/rider/junit5/ExportDataSetJUnit5It.java

Create DTD file with XML file

---

rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java
rider-core/src/test/java/com/github/database/rider/core/configuration/DBUnitConfigTest.java

added missing unit  test for #98

added unit test for new Annotation

---

rider-core/src/main/java/com/github/database/rider/core/RiderRunner.java
rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSetExecutor.java
rider-core/src/main/java/com/github/database/rider/core/api/dataset/ExpectedDataSet.java
rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
rider-core/src/test/java/com/github/database/rider/core/ExpectedDataSetReplacersIt.java

#100
Hope you'll find it useful as I did :-)

Added "replacers" to @ExpectedDataSet

---

rider-core/src/main/java/com/github/database/rider/core/util/EntityManagerProvider.java
rider-core/src/main/java/com/github/database/rider/core/util/PropertyResolutionUtil.java
rider-core/src/test/java/com/github/database/rider/core/EntityManagerDynamicOverrideTestIt.java
rider-core/src/test/java/com/github/database/rider/core/EntityManagerSystemConfigOverrideTestIt.java
rider-core/src/test/java/com/github/database/rider/core/util/PropertyResolutionUtilTest.java

Hi @rmpestano,
I created a Pull Request for the Feature discussed in the issue #105.
Hope, its gona be alright. :-)
Cheers,
Markus

Enhancement issue 105

---

rider-core/src/main/java/com/github/database/rider/core/RiderRunner.java
rider-core/src/main/java/com/github/database/rider/core/api/dataset/CompareOperation.java
rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSetExecutor.java
rider-core/src/main/java/com/github/database/rider/core/api/dataset/ExpectedDataSet.java
rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
rider-core/src/test/java/com/github/database/rider/core/ExpectedDataSetIt.java
rider-core/src/test/resources/datasets/yml/expectedUsersContains.yml

Expected dataset compare operation

---

README.adoc

Hello,
I believe there is an error in the README for the JUnit 5 module.

Fixed typo in README

---

rider-core/pom.xml
rider-core/src/main/java/com/github/database/rider/core/DBUnitRule.java
rider-core/src/main/java/com/github/database/rider/core/api/connection/ConnectionHolder.java
rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSetExecutor.java
rider-core/src/main/java/com/github/database/rider/core/connection/RiderDataSource.java
rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
rider-core/src/test/java/com/github/database/rider/core/MsSQLDatabaseIt.java
rider-core/src/test/java/com/github/database/rider/core/PostgreSQLDatabaseIt.java
rider-core/src/test/java/com/github/database/rider/core/dataset/DataSetExecutorImplTest.java

Adds disable constraints and leak hunter tests for MSSQL Server 

---

rider-examples/dbunit-tomee-appcomposer-sample/pom.xml
rider-junit5/pom.xml
rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java
rider-junit5/src/test/java/com/github/database/rider/junit5/BaseLifecycleHooks.java
rider-junit5/src/test/java/com/github/database/rider/junit5/JUnit5LifecycleHooksInSuperclassIt.java
rider-junit5/src/test/java/com/github/database/rider/junit5/JUnit5LifecycleHooksIt.java
rider-junit5/src/test/resources/datasets/expectedUsersAndTweets.yml
rider-junit5/src/test/resources/datasets/tweetAfterEach.yml
rider-junit5/src/test/resources/datasets/tweetBeforeEach.yml

Add support for @DataSet in BeforeEach and AfterEach callbacks

---

README.adoc
rider-core/src/main/java/com/github/database/rider/core/api/configuration/DBUnit.java
rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java
rider-core/src/main/java/com/github/database/rider/core/connection/RiderDataSource.java
rider-core/src/main/java/com/github/database/rider/core/exporter/DataSetExporter.java
rider-core/src/test/java/com/github/database/rider/core/configuration/DBUnitConfigTest.java
rider-core/src/test/java/com/github/database/rider/core/exporter/ExportDataSetIt.java
rider-core/src/test/resources/config/sample-dbunit.yml

Hi, please find a simple implementation to support explicit schema configuration using dbunit.yml or @DBUnit annotation, as well as when programmatically exporting a dataset.

Implermentation of #191: Support explicit schema configuration.

---

README.adoc

Using ```@DBRider``` instead ```@DBUnitInterceptor```

Fix quarkus doc

---

rider-core/src/main/java/com/github/database/rider/core/connection/RiderDataSource.java

Should fix problem with schema for MySql with default MetadataHandler

use MySqlMetadataHandler for mysql

---

README.adoc
rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSet.java
rider-core/src/main/java/com/github/database/rider/core/api/dataset/ExpectedDataSet.java
rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
rider-core/src/test/java/com/github/database/rider/core/dataset/DataSetExecutorImplTest.java

See the discussion here:
https://github.com/database-rider/database-rider/issues/209
Greetings Tom

Adds the ability to load datasets from URL

---

rider-core/src/test/java/com/github/database/rider/core/exporter/ExportDataSetIt.java

According to the Common Weakness Enumeration organization, this is a security weakness([CWE-546](https://cwe.mitre.org/data/definitions/546.html): Suspicious Comment). The comments in your code can help malicious users to find the potential presence of a bug, incomplete functionality, or weaknesses to attack the system.

Removing Suspicious Comments

---

rider-cdi/src/main/java/com/github/database/rider/cdi/DBUnitInterceptorImpl.java
rider-cdi/src/test/java/com/github/database/rider/cdi/RiderCDILifecycleHooksIt.java
rider-cdi/src/test/resources/datasets/yml/expectedTweetsAfter.yml
rider-cdi/src/test/resources/datasets/yml/expectedUsersAndTweets.yml
rider-cdi/src/test/resources/datasets/yml/userAndTweetBefore.yml

Removes junit4 dependency and adds lifecycle example

---

rider-junit5/src/main/java/com/github/database/rider/junit5/JUnit5RiderTestContext.java
rider-junit5/src/test/java/com/github/database/rider/junit5/DBUnitJUnit5It.java
rider-junit5/src/test/java/com/github/database/rider/junit5/DBUnitJUnit5NestedIt.java

add support @nested annotation for junit5

---

README.adoc
rider-core/src/main/java/com/github/database/rider/core/RiderRunner.java
rider-core/src/main/java/com/github/database/rider/core/api/configuration/DBUnit.java
rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java
rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
rider-core/src/test/java/com/github/database/rider/core/AlwaysCleanBeforeAfterIt.java
rider-core/src/test/java/com/github/database/rider/core/configuration/DBUnitConfigTest.java
rider-core/src/test/resources/config/sample-dbunit.yml

Add alwaysCleanBefore and alwaysCleanAfter DBUnit properties

---

rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java
rider-core/src/test/resources/config/sample-dbunit.yml

This PR is the follow-up for issue #379 and polishing some getter/setters.
`DBUnitConfig` doesn't have the setter of `columnSensing`. So, snakeyaml cannot set the property.

Fix not working `columnSensing` config from dbunit.yml

---

rider-core/pom.xml
rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
rider-core/src/main/java/com/github/database/rider/core/spi/DriverNameService.java
rider-core/src/main/java/com/github/database/rider/core/util/TableNameResolver.java
rider-core/src/test/java/com/github/database/rider/core/util/TableNameResolverTest.java
rider-examples/jOOQ-DBUnit-flyway-example/pom.xml
rider-examples/rider-micronaut/pom.xml
rider-examples/rider-micronaut/src/main/resources/application.yml

Fix foreign key constraint statements for H2

---

rider-core/src/main/java/com/github/database/rider/core/api/replacer/DayReplacerType.java
rider-core/src/main/java/com/github/database/rider/core/api/replacer/HourReplacerType.java
rider-core/src/main/java/com/github/database/rider/core/api/replacer/MinuteReplacerType.java
rider-core/src/main/java/com/github/database/rider/core/api/replacer/ReplacerType.java
rider-core/src/main/java/com/github/database/rider/core/api/replacer/SecondReplacerType.java
rider-core/src/main/java/com/github/database/rider/core/replacers/DateTimeReplacer.java

Hi team,
I found a typo while researching the source code.

Fix typo ReplacerType.perfix -> prefix

---

rider-core/src/main/java/com/github/database/rider/core/util/TableNameResolver.java
rider-core/src/test/java/com/github/database/rider/core/util/TableNameResolverTest.java

DBRIDER-505 = respect catalog/schema differentiation from JDBC

---

rider-core/pom.xml

Also update it to new groupId and artifactId

Correct mysql-connector dependency to scope test

---

rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSetImpl.java
rider-core/src/main/java/com/github/database/rider/core/util/AnnotationUtils.java
rider-core/src/test/java/com/github/database/rider/core/MergeDataSetsTest.java

Fixes https://github.com/database-rider/database-rider/issues/559

Dataset provider is lost during merge

---

pom.xml
rider-core/src/main/java/com/github/database/rider/core/assertion/PrologAssert.java

Updated the tuprolog version so that ANTLR version 4.10.1 is used.

Updated the version for tuprolog from 0.20.2 to 0.20.9.

---

rider-core/src/main/java/com/github/database/rider/core/api/dataset/JSONDataSet.java
rider-core/src/main/java/com/github/database/rider/core/api/dataset/MapDataSet.java
rider-core/src/test/java/com/github/database/rider/core/api/dataset/MapDataSetTest.java

Please find motivation in https://github.com/database-rider/database-rider/issues/569

Feature request #569: Extract base class MapDataSet from JSONDataSet

---

rider-core/src/main/java/com/github/database/rider/core/dataset/writer/JSONWriter.java
rider-core/src/main/java/com/github/database/rider/core/dataset/writer/YMLWriter.java
rider-core/src/test/java/com/github/database/rider/core/BinaryIt.java

fix: use java.util.Base64 instead of javax.xml.bind.DatatypeConverter for encoding Base64

---

rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
rider-core/src/test/java/com/github/database/rider/core/CleanAfterSkippingTablesIt.java

@rmpestano - could you please do the review?

#597 = add regex support for `skipCleaningFor`
