rider-cdi/src/main/java/com/github/database/rider/cdi/DataSetProcessor.java, rider-cdi/src/test/java/com/github/database/rider/cdi/BeforeAndAfterTest.java, rider-core/src/main/java/com/github/database/rider/core/DBUnitRule.java, rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSetExecutor.java, rider-core/src/main/java/com/github/database/rider/core/connection/ConnectionHolderImpl.java, rider-core/src/main/java/com/github/database/rider/core/connection/RiderDataSource.java, rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java, rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java
Database-rider opens multiple connections if connection pool was used and DBUnitRule initialized like
```
@Rule
public DBUnitRule dbUnitRule = DBUnitRule.instance(() -> datasource.getConnection());
```
This can lead to a freezing tests when all connections from the pool obtained. It can also break the functionality of disabling constraints
=> Cache connections

rider-cdi/src/main/java/com/github/database/rider/cdi/DBUnitInterceptorImpl.java
When we have many tests in one module and one of them falls then all remained tests can fall down because transaction is not closed.
In such case catch section is not executed because assert checking throws instance of Throwable (not Exception).
=> Transactional interceptor doesn't close transaction when test falls down by assert

rider-cdi/src/main/java/com/github/database/rider/cdi/DBUnitInterceptorImpl.java, rider-cdi/src/main/java/com/github/database/rider/cdi/DataSetProcessor.java, rider-core/src/main/java/com/github/database/rider/core/AbstractRiderTestContext.java, rider-core/src/main/java/com/github/database/rider/core/DBUnitRule.java, rider-core/src/main/java/com/github/database/rider/core/JUnit4RiderTestContext.java, rider-core/src/main/java/com/github/database/rider/core/RiderRunner.java, rider-core/src/main/java/com/github/database/rider/core/RiderTestContext.java, rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSetExecutor.java, rider-core/src/main/java/com/github/database/rider/core/api/leak/LeakHunter.java, rider-core/src/main/java/com/github/database/rider/core/connection/RiderDataSource.java, rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java, rider-core/src/main/java/com/github/database/rider/core/leak/AbstractLeakHunter.java, rider-core/src/main/java/com/github/database/rider/core/leak/H2LeakHunter.java, rider-core/src/main/java/com/github/database/rider/core/leak/HsqlDBLeakHunter.java, rider-core/src/main/java/com/github/database/rider/core/leak/LeakHunterException.java, rider-core/src/main/java/com/github/database/rider/core/leak/LeakHunterFactory.java, rider-core/src/main/java/com/github/database/rider/core/leak/MySqlLeakHunter.java, rider-core/src/main/java/com/github/database/rider/core/leak/OracleLeakHunter.java, rider-core/src/main/java/com/github/database/rider/core/leak/PostgreLeakHunter.java, rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java, rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitTestContext.java, rider-junit5/src/main/java/com/github/database/rider/junit5/JUnit5RiderTestContext.java, rider-junit5/src/test/java/com/github/database/rider/junit5/WithoutDataSetIt.java
Extracting test runner logic in junit agnostic class allows:
- delete repeated test runner logic from modules. 
I have combined the logic in core and juni5 module thereby fixing connection leaks in junit5
- simplify writing custom runners. For example spring extension, that allow automatic registering connection from application context. If you are interested I can send that extension in another PR.
=> Extract test runner logic in junit agnostic class

rider-core/src/main/java/com/github/database/rider/core/api/configuration/DBUnit.java, rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java, rider-core/src/main/java/com/github/database/rider/core/connection/RiderDataSource.java, rider-core/src/test/java/com/github/database/rider/core/configuration/DBUnitConfigTest.java, rider-core/src/test/resources/config/sample-dbunit.yml
Added availability to explicitly specify datatypeFactory property for dbUnit:
1) via @DBUnit with dataTypeFactoryClass property
2) via dbunit.yml with properties.datatypeFactory
If one of this property was specified, then default resolving method would be skipped.
=> Allow to specify custom DataTypeFactory (issue #30)

rider-spring/src/main/java/com/github/database/rider/spring/SpringRiderTestContext.java, rider-spring/src/test/java/com/github/database/rider/spring/dataset/MetaDataSet.java, rider-spring/src/test/java/com/github/database/rider/spring/dataset/MetaDataSetIT.java, rider-spring/src/test/java/com/github/database/rider/spring/dataset/MetaDataSetTest.java
This PR allows database-rider annotations to be used as meta-annotations. Fixes #79 for `rider-spring` module
=> Allow DB Rider annotations to be used as meta-annotations (rider-spring)

rider-core/src/main/java/com/github/database/rider/core/api/configuration/DBUnit.java, rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java, rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java, rider-core/src/main/java/com/github/database/rider/core/replacers/DateTimeReplacer.java, rider-core/src/main/java/com/github/database/rider/core/replacers/NullReplacer.java, rider-core/src/main/java/com/github/database/rider/core/replacers/Replacer.java, rider-core/src/main/java/com/github/database/rider/core/replacers/UnixTimestampReplacer.java, rider-core/src/test/java/com/github/database/rider/core/configuration/DBUnitConfigTest.java, rider-core/src/test/java/com/github/database/rider/core/model/Tweet.java, rider-core/src/test/java/com/github/database/rider/core/model/lowercase/Tweet.java, rider-core/src/test/java/com/github/database/rider/core/replacers/CustomReplacementIt.java, rider-core/src/test/java/com/github/database/rider/core/replacers/CustomReplacer.java, rider-core/src/test/java/com/github/database/rider/core/replacers/DateReplacementsIt.java, rider-core/src/test/java/com/github/database/rider/core/replacers/NullReplacementsIt.java, rider-core/src/test/resources/config/sample-dbunit.yml, rider-core/src/test/resources/datasets/yml/custom-replacements.yml, rider-core/src/test/resources/datasets/yml/date-replacements.yml, rider-core/src/test/resources/datasets/yml/null-replacements.yml
- Added `UnixTimestampReplacer`, which replaces _[UNIX_TIMESTAMP]_ with actual unix timestamp, as requested in #61 
- Added `NullReplacer`, which replaces _[null]_ with actual `null` value, as requested in #52 
- Added ability for user to register custom replacers, by implementing `Replacer` interface and then registering all replacers in global config, or referencing them via `@DBunit#replacers`. The latter will merge specified replacers with defaults, which are at this moment the two mentioned above + `DateTimeReplacer`, (already part of Database Rider). Fixes #52
=> Custom replacers + NullReplacer, UnixTimestampReplacer

rider-core/src/main/java/com/github/database/rider/core/RiderRunner.java, rider-core/src/main/java/com/github/database/rider/core/api/dataset/DataSetExecutor.java, rider-core/src/main/java/com/github/database/rider/core/api/dataset/ExpectedDataSet.java, rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java, rider-core/src/test/java/com/github/database/rider/core/DataSetExecutorIt.java, rider-core/src/test/java/com/github/database/rider/core/ExpectedDataSetIt.java, rider-core/src/test/resources/datasets/yml/expectedUsersIgnoreOrder.yml
When using ignoreOrder=true with @ExpectedDataSet Database Rider will take the columns from the expected dataset and use those to sort the actual and expected dataset rows before comparison.
=> Add orderBy option to @ExpectedDataSet

rider-core/src/main/java/com/github/database/rider/core/configuration/GlobalConfig.java, rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
Transforming from `someString.equals("string")`  to `"string".equals(someString)`. This avoids checking for `null` and also prevents `NullPointerException` being thrown.
These fixes SonarQube violations of the rule: [Strings literals should be placed on the left side when checking for equality](https://rules.sonarsource.com/java/RSPEC-1132)
=> SonarQube - String Literals on the left on comparisons

rider-core/src/main/java/com/github/database/rider/core/api/dataset/ScriptableTable.java, rider-core/src/main/java/com/github/database/rider/core/assertion/DataSetAssert.java, rider-core/src/main/java/com/github/database/rider/core/exporter/DataSetExporter.java
Replacing `String.lastIndexOf("/")` with `String.lastIndexOf('/')` which can be more performant.
This fixes SonarQube violations of the rule: [String function use should be optimized for single characters](https://rules.sonarsource.com/java/RSPEC-3027)
=> SonarQube - Optimizing String.lastIndexOf() for single char

rider-core/src/main/java/com/github/database/rider/core/dataset/builder/DataSetBuilder.java
Iterating on a Map using `entrySet()`, when both key and value are needed, is more performant.
Fix a SonarQube violation of the rule: ["entrySet()" should be iterated when both the key and value are needed](https://rules.sonarsource.com/java/RSPEC-2864)
=> SonarQube - Iterating on entrySet() instead of keySet() when key and value are needed

rider-core/src/perf/java/com/github/database/rider/RiderDataSetBenchmark.java
Extracting constants from Strings that were duplicated at least 3 times. Considering only Strings with length >= 5.
This fixes SonarQube issues for the rule: [String literals should not be duplicated](https://rules.sonarsource.com/java/RSPEC-1192)
=> SonarQube - Extracting constants from duplicated Strings

rider-core/src/main/java/com/github/database/rider/core/dataset/writer/JSONWriter.java, rider-core/src/test/java/com/github/database/rider/core/exporter/ExportNullPropertiesIt.java
During exporting database data to json file in the case when last values are null then there is added extra comma that is not valid json format
I mean, when we have a row with the next values:
```
|   column_1   | column_2 | column_3 | column_4 |
| -------------| -------- | -------- | -------- |
|  some value  |   null   |    42    |   null   |
```
then will be generated next json with the extra comma in the last object parameter
```(javascript)
{
"tableName":[
{
"column_1": "some value",
"column_3": 42,
}
]
}
```
=> fix bug with extra comma in json object

rider-core/src/main/java/com/github/database/rider/core/dataset/writer/JSONWriter.java, rider-core/src/test/java/com/github/database/rider/core/exporter/ExportSomeNullPropertiesIt.java, rider-core/src/test/java/com/github/database/rider/core/exporter/ExportStringPropertyWithNewLineSymbolIt.java
1. After the last version json export was a little bit broken (sorry:-)). In some cases in fields were saved not relevant values.
2. Also, json export did not work correctly in the case when in the field was stored multiline text.
=> Add support for multiline strings in json export

rider-spring/pom.xml
without being test scoped (like it is in all of the other dbrider modules), `rider-spring` exports an unnecessary implementation of `slf4j-api`, causing conflicts in any projects that depend upon it, forcing them to add an `<exclusion/>` to the dependency that they otherwise would not need to do.
=> in rider-spring/pom.xml, the dependency slf4j-simple should be test scoped

rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
I have a system running with Postgres 9.6 where all database table names are lowercase, except for one table used by Flyway to track updates, which is in uppercase.
When running a test which disables constraints, the test fails because of an an error in the generated sql statement for this table:
postgres> ERROR:  relation "myschema.schema_updates" does not exist
postgres> STATEMENT:  ALTER TABLE myschema.SCHEMA_UPDATES DISABLE TRIGGER ALL
This is the annotation I'm using for the test:
```
@Test
@DataSet(
value = {"mydataset.xml"},
disableConstraints = true,
cleanBefore = true,
strategy = SeedStrategy.INSERT"
)
```
This SCHEMA_UPDATES table is only accessed correctly when the table name is escaped. Something like this:
```
ALTER TABLE myschema."SCHEMA_UPDATES" DISABLE TRIGGER ALL
Query …
```
=> Apply DBUnit escape pattern when getting table names

rider-core/src/main/java/com/github/database/rider/core/api/configuration/DBUnit.java, rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java, rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java, rider-core/src/test/java/com/github/database/rider/core/DBUnitColumnSensingIt.java, rider-core/src/test/resources/datasets/xml/user-with-omitted-columns.xml
I've been trying to use a dataset with some rows where some columns are omitted (because of null values), but any column not specified on the first row gets ignored by DBUnit. There's a feature named ["column sensing"](http://dbunit.sourceforge.net/faq.html#differentcolumnnumber) that can be used in this situation, but I've been unable to enable it through Database Rider. I've searched in the issues list and the closed pull requests, but I haven't found anything.
This is a first attempt at passing that configuration to DBUnit. Although this works in the project where I'm using it, please consider it as a work in progress. Before trying to do some integration tests, please let me know if you have any ideas, concerns, etc. Thank you.
=> Add support for column sensing feature in FlatXML

rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
This pull-request is for issue https://github.com/database-rider/database-rider/issues/202.
* Decorating the [com.github.database.rider.core.dataset.DataSetExecutorImpl#clearDatabase](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L603) method with [disableConstraints()](https://github.com/database-rider/database-rider/blob/b03cf80002ab82e7f918aa56aa8852896f3bac77/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L326) call before and with [enableConstraints()](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L389) call after.
=> Disable foreign key constraint violation when cleaning database

README.adoc, rider-core/src/main/java/com/github/database/rider/core/configuration/DataSetConfig.java, rider-core/src/main/java/com/github/database/rider/core/dsl/RiderDSL.java, rider-core/src/test/java/com/github/database/rider/core/dsl/RiderDSLIt.java, rider-core/src/test/java/com/github/database/rider/core/replacers/CustomReplacementIt.java
This is an attempt on creating a DSL to create datasets instead of using annotations.
The annotation approach is great and does a good job separating test configuration from test logic. 
The main issue with annotation approach is that it is dependent on the test run engine which reads the annotation and then creates the dataset.
So for example, if you use cucumber you cannot use annotation approach and have to deal with DataSetExecutor directly which is not so fluent API.
Also, the annotations will not help when dealing with multiple databases on the [same test](https://github.com/database-rider/database-rider/blob/d02c236c2e59fef336c39bc78de6872f0ce63f5e/rider-core/src/test/java/com/github/database/rider/core/MultipleDataBasesIt.java#L45), you can only specify an executor ID per test …
=> Adds RiderDSL to make it possible to populate database in a fluent way.

rider-core/src/main/java/com/github/database/rider/core/dsl/RiderDSL.java
Fixes the RiderDSL ThreadLocal getInstance() method.
=> RiderDSL: one instance per thread

rider-examples/quarkus-dbunit-sample/src/main/resources/application.properties
Hard coded passwords are bad. But the examples are show cases only which should be easy to read.
Closes #218
=> Add a remark to use encrypted passwords only

rider-cdi/src/test/java/com/github/database/rider/cdi/DBUnitCDIIt.java
According to the Common Weakness Enumeration organization, this is a security weakness([CWE-546](https://cwe.mitre.org/data/definitions/546.html): Suspicious Comment). The comments in your code can help malicious users to find the potential presence of a bug, incomplete functionality, or weaknesses to attack the system.
=> Removing Suspicious Comments

README.adoc, rider-core/src/main/java/com/github/database/rider/core/api/configuration/DBUnit.java, rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java, rider-core/src/main/java/com/github/database/rider/core/connection/RiderDataSource.java, rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java, rider-core/src/test/java/com/github/database/rider/core/configuration/DBUnitConfigTest.java, rider-core/src/test/java/com/github/database/rider/core/connection/RiderDataSourceIT.java, rider-core/src/test/resources/config/sample-dbunit.yml
Add "expectedDbType" config option for DBUnit and dbunit.yml.
In the process of initialization, if the actual database type is different from the expected database type, exception will be thrown unless the expected database type is `UNKNOWN`. Default is `UNKNOWN`.
Close #227 .
=> Feature request: Limit the database type. #227

rider-core/src/main/java/com/github/database/rider/core/api/dataset/SeedStrategy.java, rider-core/src/test/java/com/github/database/rider/core/MsSQLDatabaseIt.java
Added IDENTITY_INSERT SeedStrategy to avoid following error:
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot insert explicit value for identity column in table 'xxxxx' when IDENTITY_INSERT is set to OFF.
=> Patch for using DB Rider with MS SQL Server

rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
keeping default connection autoCommit configuration when creating a DataSet.
Tests are passing so I am assuming forcing autoCommit to true when creating the DataSet is not necessary.
=> #365 Spring @Transactional tests is broken

rider-core/pom.xml, rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
DataSetExecutorImpl#clearDatabase method does not take table ordering configuration into account as it puts all the delete statements in a HashSet, which is a Set implementation that does not guarantee any ordering.
Fixes https://github.com/database-rider/database-rider/issues/417
=> Table ordering is not taken into account

.github/workflows/ci.yml
Currently, the release job is always triggered on Pull Requests, but the actual release steps are skipped.
By using `job.if` you can skip the whole job if we're not on the master branch.
=> Only run release job in master

rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
Create the SQL statement with default cursor & concurrency option in `executeStatements(String... statements)`.
This allows it to work with SQLite. Beside we don't use the returned ResultSet anyway.
=> Execute statement with default options

rider-core/src/main/java/com/github/database/rider/core/configuration/DataSetConfig.java, rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java, rider-core/src/test/java/com/github/database/rider/core/configuration/DataSetConfigTest.java
See motivation in https://github.com/database-rider/database-rider/issues/567.
Changes:
* Overload datasetProvider() to allow configuration using either class or instance.
* Moved instantiation of DataSetProvider class from DataSetExecutorImpl into DataSetConfig::datasetProvider().
* Added corresponding unit test case.
=> Feature Request #567: allow configuration of DataSetProvider instance

rider-core/src/main/java/com/github/database/rider/core/configuration/DBUnitConfig.java, rider-core/src/main/java/com/github/database/rider/core/configuration/SnakeYamlHelper.java
SnakeYaml 2.0 solved the unsafe deserialization vulnerability by changing the default behavior of constructed `Yaml` instance to restrict types which can be instantiated during deserialization.
This behavior made impossible to define custom DataSet replacers in YAML as they must be instantiated during deserialization.
E.g.
```
caseInsensitiveStrategy: !!com.github.database.rider.core.api.configuration.Orthography 'LOWERCASE'
properties:
replacers: [!!my.package.WktReplacer {}]
```
Both `Orthography` enum and `WktReplacer` could not be instantiated during YAML deserialization.
This commit fixes this behavior by configuring SnakeYAML 2.x to use the old behavior (allow any class to be instantiated).
This is acceptable solution as `dbunit.yml` is loaded from the trusted source, so the …
=> Add SnakeYAML 2.x compatibility

rider-cdi/src/test/java/com/github/database/rider/cdi/ExportDataSetCDIIt.java, rider-core/src/main/java/com/github/database/rider/core/exporter/DataSetExporter.java, rider-core/src/test/java/com/github/database/rider/core/exporter/ExportDataSetIt.java
The tables exported with ExportDataSet have no ordining.
These bothe ExportDataSet instructions are generateing the same export files:
-   @ExportDataSet(includeTables = {"PRODUCT","SUBPRODUCT"}, dependentTables = true)
-   @ExportDataSet(includeTables = {"SUBPRODUCT","PRODUCT"}, dependentTables = true)
Changing the code from HashMap to LinkedHashMap is givin the developer the control of the table ordering.
=> keeping table export ordering indicated in "includeTables"

rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java
Hi, @rmpestano 
Recently, I have been working on a project using database-rider, and I encountered a situation where I needed to use both the value and provider attributes of the @DataSet annotation simultaneously. When I used them together, the execution completed without any logs, leading me to believe that everything was applied correctly. However, upon further inspection, I realized that neither attribute was actually applied.
I had to debug the internal logic step by step to discover that both attributes were not being applied. Some of my team members also went through the same trouble as I did.
Therefore, I believe that logging the following message when both the value and provider attributes of the @DataSet annotation are used together would save others from experiencing the same …
=> add dataset value attribute and provider attribute duplication use log

rider-examples/spring-boot-dbunit-sample/src/test/java/com/github/database/rider/springboot/LeakingConnectionsTest.java, rider-junit5/src/main/java/com/github/database/rider/junit5/DBUnitExtension.java, rider-junit5/src/main/java/com/github/database/rider/junit5/integration/Micronaut.java, rider-junit5/src/main/java/com/github/database/rider/junit5/integration/Spring.java, rider-junit5/src/main/java/com/github/database/rider/junit5/jdbc/ConnectionManager.java
Current implementation doesn't support @DbRider in callback methods. It makes impossible to set up test data into several independent datasources.  This pr makes working such approach:
```java
@BeforeAll
@DBRider(dataSourceBeanName = "firstDataSource")
@DataSet(value = "test-data-1.xml")
static void setUpDataInFirstDb() {
}
@BeforeAll
@DBRider(dataSourceBeanName = "secondDataSource")
@DataSet(value = "test-data-2.xml", disableConstraints = true)
static void setUpDataInSecondDb() {
}
```
=> Respect @DBRider in junit5 @BeforeAll, @BeforeEach, @AfterAll, @AfterEach methods
